apiVersion: v1
kind: Service
metadata:
  name: qwen-tiny
  namespace: models
spec:
  selector:
    serving.kserve.io/inferenceservice: qwen-tiny
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
